package com.github.Franfuu.model.entity;

public enum MachineType {
    CINTA_DE_CORRER,
    MÁQUINA_ELÍPTICA,
    BICICLETA_ESTÁTICA,
    MÁQUINA_DE_REMO,
    MÁQUINA_DE_PRESS_DE_PECHO,
    MÁQUINA_DE_PRENSA_DE_PIERNAS,
    MÁQUINA_DE_POLEA,
    MÁQUINA_DE_CURL_DE_BÍCEPS,
    MÁQUINA_DE_EXTENSIÓN_DE_PIERNAS,
    MÁQUINA_DE_ABDOMINALES,
    MÁQUINA_DE_PRESS_MILITAR,
    MÁQUINA_DE_GLÚTEOS,
    MÁQUINA_DE_ABDUCTORES,
    MÁQUINA_DE_TRÍCEPS,
    MÁQUINA_DE_PRENSA_DE_HOMBROS
}
